language: python
python:
  - "3.8"
sudo: required
services:
  - postgresql
  - docker
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "create database ikea;"
  - psql -c "create user ikea with password 'ikea';" -U postgres
  - psql -c "grant all privileges on database ikea to ikea;" -U postgres
script:
  - cd src/ && flask db drop && flask db create && python -m unittest tests/client.py
  #- flake8 .
after_success:
  - ./travis/deploy.sh
