language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
# Run tests
script:
  # Unit Tests
  - cd src/ && flask db drop && flask db create && python -m unittest tests/client.py
  # Linting Tests
  - flake8 .
